name: GetScreen RDP Setup

on:
  workflow_dispatch:

jobs:
  setup-rdp:
    runs-on: windows-latest

    steps:
      - name: Set Up GetScreen RDP
        run: |
          # Explicitly call PowerShell to execute PowerShell commands
          powershell -Command "
            # Write the email to a secrets.txt file
            'EMAIL_SECRET=zeshan.bwptrade52@gmail.com' | Out-File -FilePath secrets.txt -Encoding utf8

            # Download GetScreen installer
            Invoke-WebRequest -Uri 'https://getscreen.me/download/windows/installer' -OutFile 'GetScreenInstaller.exe'

            # Run the installer silently
            Start-Process -FilePath 'GetScreenInstaller.exe' -ArgumentList '/silent' -NoNewWindow -Wait

            # Confirm installation
            Write-Output 'GetScreen client installed successfully.'
          "
